# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0d30d645170484c1c56fb1713159935039055ff87492ad4ac76c99932845d5103fda75b21db924fd6a7aed0c13f28d15fd5ea7409a3db0dba5515c56f323a10

test:
  secret_key_base: cf418e1d19995c0c5412001c8e36a67a610997d5cc61c9605c393302ffc02475d41a277205b3928e815f85f29de0f4e1047e824ff83ff79dcb1b8c6a4a151ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
